### ISSUE TITLE
这个怎么用呀?

### ISSUE THREAD

**Issue by 448808614** [ElpsyCN/el-bot-web#1]

**Comment by YunYouJun** [comment]
直接访问 <https://bot.elpsy.cn> 填写信息，可以通过 mirai-api-http 与你的 QQ 机器人建立连接，实际上现在只有简单的发送信息功能，以避免顶掉自己的机器人而可以使用机器人发消息。
主要在维护 [el-bot](https://github.com/YunYouJun/el-bot)，所以这边鸽了挺长时间，以及也没发现有啥特殊的需求。
